//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarioKart.UI
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OBJI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OBJI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarioKart.UI.OBJI", typeof(OBJI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_2D01 {
            get {
                object obj = ResourceManager.GetObject("OBJ_2D01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_2E01 {
            get {
                object obj = ResourceManager.GetObject("OBJ_2E01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_3501 {
            get {
                object obj = ResourceManager.GetObject("OBJ_3501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_3801 {
            get {
                object obj = ResourceManager.GetObject("OBJ_3801", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_3A01 {
            get {
                object obj = ResourceManager.GetObject("OBJ_3A01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_3E01 {
            get {
                object obj = ResourceManager.GetObject("OBJ_3E01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_3F01 {
            get {
                object obj = ResourceManager.GetObject("OBJ_3F01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_4901 {
            get {
                object obj = ResourceManager.GetObject("OBJ_4901", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_5901 {
            get {
                object obj = ResourceManager.GetObject("OBJ_5901", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_6500 {
            get {
                object obj = ResourceManager.GetObject("OBJ_6500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_6700 {
            get {
                object obj = ResourceManager.GetObject("OBJ_6700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_6800 {
            get {
                object obj = ResourceManager.GetObject("OBJ_6800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_6B00 {
            get {
                object obj = ResourceManager.GetObject("OBJ_6B00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_6D00_2 {
            get {
                object obj = ResourceManager.GetObject("OBJ_6D00_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_6D00_3 {
            get {
                object obj = ResourceManager.GetObject("OBJ_6D00_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_6E00 {
            get {
                object obj = ResourceManager.GetObject("OBJ_6E00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_9101 {
            get {
                object obj = ResourceManager.GetObject("OBJ_9101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_9601 {
            get {
                object obj = ResourceManager.GetObject("OBJ_9601", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_9801 {
            get {
                object obj = ResourceManager.GetObject("OBJ_9801", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_9901 {
            get {
                object obj = ResourceManager.GetObject("OBJ_9901", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_9B01 {
            get {
                object obj = ResourceManager.GetObject("OBJ_9B01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_A401 {
            get {
                object obj = ResourceManager.GetObject("OBJ_A401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_A501 {
            get {
                object obj = ResourceManager.GetObject("OBJ_A501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_A601 {
            get {
                object obj = ResourceManager.GetObject("OBJ_A601", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_A701 {
            get {
                object obj = ResourceManager.GetObject("OBJ_A701", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_A801 {
            get {
                object obj = ResourceManager.GetObject("OBJ_A801", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_A901 {
            get {
                object obj = ResourceManager.GetObject("OBJ_A901", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_AC01 {
            get {
                object obj = ResourceManager.GetObject("OBJ_AC01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_AF01 {
            get {
                object obj = ResourceManager.GetObject("OBJ_AF01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_B001 {
            get {
                object obj = ResourceManager.GetObject("OBJ_B001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_B301 {
            get {
                object obj = ResourceManager.GetObject("OBJ_B301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_C900 {
            get {
                object obj = ResourceManager.GetObject("OBJ_C900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_CB00 {
            get {
                object obj = ResourceManager.GetObject("OBJ_CB00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_CD00 {
            get {
                object obj = ResourceManager.GetObject("OBJ_CD00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_CE00 {
            get {
                object obj = ResourceManager.GetObject("OBJ_CE00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OBJ_CF00 {
            get {
                object obj = ResourceManager.GetObject("OBJ_CF00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
